"""
Django settings for eaglesbrandsolutions project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from django.contrib.messages import constants as messages
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
STATIC_ROOT = '/home/eaglyxow/development.eaglesbrandsolutions.com/static'
STATIC_DIR = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATICFILES_DIRS = [STATIC_DIR,]

FONTAWESOME_5_CSS = 'fontawesome_5/css/django-fontawesome.css'

EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey' #this is exactly the value 'apikey'
EMAIL_HOST_PASSWORD = config('SENDGRIG_API')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
FROM_HOST = 'EaglesBrand Integrated Engineering Solutions Limited <info@eaglesbrandsolutions.com>'
RECIEVER_MAIL = ['info@eaglesbrandsolutions.com', 'nonwaz78@gmail.com',]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o(m6r6)itk^!r5gd-k#$ok9s$z5_hm@mxbhq-n0ev7zz_yk%!y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eaglesbrandapp',
    'fontawesome_5',
    'tinymce',
    'filebrowser',
   

]

TINYMCE_DEFAULT_CONFIG = {
 'height': 360,
 'width': 720,
 'cleanup_on_startup': True,
 'custom_undo_redo_levels': 20,
 'selector': 'textarea',
 'theme': 'modern',
 'plugins': '''
 textcolor save link image media preview codesample contextmenu
 table code lists fullscreen insertdatetime nonbreaking
 contextmenu directionality searchreplace wordcount visualblocks
 visualchars code fullscreen autolink lists charmap print hr
 anchor pagebreak
 ''',
 'toolbar1': '''
 fullscreen preview bold italic underline | fontselect,
 fontsizeselect | forecolor backcolor | alignleft alignright |
 aligncenter alignjustify | indent outdent | bullist numlist table 
|
 | link image media | codesample |
 ''',
 'toolbar2': '''
 visualblocks visualchars |charmap hr pagebreak nonbreaking anchor | code |
 ''',
 'contextmenu': 'formats | link image',
 'menubar': True,
 'statusbar': True,
 }



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ogunburebusayo.j@gmail.com'
EMAIL_HOST_PASSWORD = 'bussyboo98'




MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

ROOT_URLCONF = 'eaglesbrandsolutions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eaglesbrandsolutions.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

