# Generated by Django 3.2.5 on 2021-07-31 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            
                ('image1', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('our_vision', models.TextField(blank=True, null=True, verbose_name='Our Vision')),
                ('our_mission', models.TextField(blank=True, null=True, verbose_name='Our Mission')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('slug', models.SlugField(unique=True)),
                ('pst_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Post Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50, verbose_name='Posted By')),
                ('pst_image1', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Author Image')),
                ('content1', models.TextField(max_length=300, verbose_name='Blog Summary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name_plural': 'Blog Post',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_title', models.CharField(max_length=150, verbose_name='Project Title')),
                ('slug', models.SlugField(unique=True)),
                ('pst_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Project Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_title', models.CharField(max_length=150, verbose_name='Service Title')),
                ('slug', models.SlugField()),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('pst_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Service Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name='User Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField(verbose_name='Content')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eaglesbrandapp.blogpost')),
            ],
        ),
    ]
