# Generated by Django 3.2.5 on 2021-07-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=1, max_length=50, verbose_name='Posted By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pst_image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Author Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(),
        ),
    ]
