# Generated by Django 3.2.5 on 2021-08-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0003_about_our_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_text', models.CharField(blank=True, max_length=100, null=True)),
                ('slide_content1', models.TextField(blank=True, null=True)),
                ('slide_content2', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Home Slider',
            },
        ),
    ]
