# Generated by Django 3.2.5 on 2021-07-24 16:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content1',
            field=models.TextField(default=1, max_length=300, verbose_name='Blog Summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
