# Generated by Django 3.2.5 on 2021-08-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0005_partners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
