# Generated by Django 3.2.5 on 2021-07-24 16:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0005_auto_20210724_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('slug', models.SlugField(unique=True)),
                ('pst_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Post Image')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Project',
            },
        ),
    ]
