# Generated by Django 3.2.5 on 2021-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0006_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pst_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Project Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pst_title',
            field=models.CharField(max_length=150, verbose_name='Project Title'),
        ),
    ]
