# Generated by Django 3.2.5 on 2021-07-24 18:52

from django.db import migrations, models
import fontawesome_5.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0007_auto_20210724_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pst_title', models.CharField(max_length=150, verbose_name='Service Title')),
                ('slug', models.SlugField()),
                ('icon', fontawesome_5.fields.IconField(blank=True, max_length=60)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='This will automatically add a time when you click save')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
