# Generated by Django 3.2.5 on 2021-07-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eaglesbrandapp', '0008_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='pst_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Project Image'),
        ),
    ]
